version: '3.8'
services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile
    command: 'python main.py'
    ports:
      - "8001:5001"
    volumes:
      - .:/app
      #segun la documentaci贸n se debe asociar el volumen de ejecuci贸n Socket en la imagen de base de datos como en el app
      - .databaseUnix:/var/run/mysqld
    depends_on:
      - db

  queue:
    build:
      context: .
      dockerfile: Dockerfile
    command: 'python consumer.py'
    depends_on:
      - db

  db:

    image: mysql
    restart: always
    volumes:
      - .database:/var/lib/mysql
      #segun la documentaci贸n se debe asociar el volumen de ejecuci贸n Socket en la imagen de base de datos como en el app
      - .databaseUnix:/var/run/mysqld      
    ports:
      - "33067:3306" 
    environment:      
      MYSQL_DATABASE: 'main'
      MYSQL_USER: 'django'
      MYSQL_PASSWORD: 'mysql1234pass'
      MYSQL_ROOT_PASSWORD: 'password'      
